Use DiagnosticStatus.msg values instead of creation bytes manually
ros/diagnostics pull request #193
Opened 2021-03-08 21:33 UTC by BasVolkers

2021-03-08 22:10 UTC, BasVolkers commented
@Karsten1987 I'm tagging you since you merged the previous request.

2021-03-09 07:03 UTC, norro requested changes
This indeed seems very reasonable and should make it more robust. The robot monitor plugin somehow stopped to be working for me yesterday so I couldn't check with it. But other than that everything seems to be working.
Could you please have a look at linter issues, though?!

2021-03-09 07:04 UTC, norro commented on diagnostic_updater/test/diagnostic_updater_test.py
> +        self.assertEqual(DiagnosticStatus.WARN, stat[3].level, 'min frequency exceeded but not reported')
Lines 109 - 112 are > 99 characters
```
6: ./test/diagnostic_updater_test.py:109:100: E501 line too long (105 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.WARN, stat[0].level, 'max frequency exceeded but not reported')
6:                                                                                                    ^
6: 
6: ./test/diagnostic_updater_test.py:110:100: E501 line too long (103 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.OK, stat[1].level, 'within max frequency but reported error')
6:                                                                                                    ^
6: 
6: ./test/diagnostic_updater_test.py:111:100: E501 line too long (103 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.OK, stat[2].level, 'within min frequency but reported error')
6:                                                                                                    ^
6: 
6: ./test/diagnostic_updater_test.py:112:100: E501 line too long (105 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.WARN, stat[3].level, 'min frequency exceeded but not reported')
6: ./test/diagnostic_updater_test.py:109:100: E501 line too long (105 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.WARN, stat[0].level, 'max frequency exceeded but not reported')
6:                                                                                                    ^
6: 
6: ./test/diagnostic_updater_test.py:110:100: E501 line too long (103 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.OK, stat[1].level, 'within max frequency but reported error')
6:                                                                                                    ^
6: 
6: ./test/diagnostic_updater_test.py:111:100: E501 line too long (103 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.OK, stat[2].level, 'within min frequency but reported error')
6:                                                                                                    ^
6: 
6: ./test/diagnostic_updater_test.py:112:100: E501 line too long (105 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.WARN, stat[3].level, 'min frequency exceeded but not reported')
6: ./test/diagnostic_updater_test.py:109:100: E501 line too long (105 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.WARN, stat[0].level, 'max frequency exceeded but not reported')
6:                                                                                                    ^
6: 
6: ./test/diagnostic_updater_test.py:110:100: E501 line too long (103 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.OK, stat[1].level, 'within max frequency but reported error')
6:                                                                                                    ^
6: 
6: ./test/diagnostic_updater_test.py:111:100: E501 line too long (103 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.OK, stat[2].level, 'within min frequency but reported error')
6:                                                                                                    ^
6: 
6: ./test/diagnostic_updater_test.py:112:100: E501 line too long (105 > 99 characters)
6:         self.assertEqual(DiagnosticStatus.WARN, stat[3].level, 'min frequency exceeded but not reported')
```

2021-03-15 10:17 UTC, BasVolkers commented on diagnostic_updater/test/diagnostic_updater_test.py
> +        self.assertEqual(DiagnosticStatus.WARN, stat[3].level, 'min frequency exceeded but not reported')
Will fix this!

2021-10-18 13:30 UTC, clalancette approved these changes

2021-10-18 13:31 UTC, merged