Ros2cli diagnostics
ros/diagnostics pull request #301
Opened 2023-04-26 18:27 UTC by robobe

Add ros2cli for diagnostics as alternative for diagnostics_analysis
The project add `diagnostics` command to ROS2 cli with there verbs.
- list
- show
- csv

check README.md for more

2023-04-26 19:19 UTC, ct2034 commented on ros2diagnostics_cli/package.xml
> +  <depend>python3-pyyaml</depend>
```suggestion
  <depend>python3-yaml</depend>
```
I think this is the right rosdep key

2023-04-26 19:21 UTC, ct2034 requested changes
Hi @robobe. Thanks for your PR. This looks amazing. :grin: 
I hope I fill find the time for a proper review soon. Just something I noticed:
- All source files are missing copyright headers
- Please update the package.xml and do what else is required for the buildfarm to run.

2023-05-04 09:40 UTC, ct2034 requested changes
Please move the work on diagnostics_tutorial to a separate PR, such that I can review the `ros2diagnostics_cli` separately. And if you are still working on this, please use the draft PR feature. Otherwise, this creates a lot of overhead. Some points:

- Please add your package under https://github.com/robobe/diagnostics/blob/98b78aaa544b5ad06b4810d61bd5394b425f2013/.github/workflows/lint.yaml#L38-L39 and https://github.com/robobe/diagnostics/blob/98b78aaa544b5ad06b4810d61bd5394b425f2013/.github/workflows/test.yaml#L19-L20 so that it is checked in the github ci.
- The package.xml needs some fields filled. The version must be the same as the other packages in this repo. You can add me as a maintainer and yourself as author if you like.
- Similar things apply to the setup.py
- I am not quite sure what the two verbs `show` and `list` do. Both seem to have a functionality that I would call `echo` at least when compared to how the `topic` verb does things.
- What does the `world` verb do? It does not seem to be documented.

In general this seems very work in progress. Please make this a draft PR, then.

2023-05-04 09:42 UTC, ct2034 commented
I was able to make it into a draft myself, nvm. Just click `Ready for review` when you are. Or let me know when you need help. I generally suggest to focus on one or two well-implemented verbs and extend on it later.

2023-05-17 12:33 UTC, ct2034 requested changes
Can you please describe the intended use case for the list and show verb? I feel like there is an overlap. In my opinion, two verbs are required: 
list - it lists all available diagnostics sources and the exits
echo - it will run forever and echo all the diagnostics info on a specific source.
Basically similar to how theses two verbs work for the topic command right now

2023-05-17 12:33 UTC, ct2034 commented on ros2diagnostics_cli/ros2diagnostics_cli/api/__init__.py
> +        raise Exception(
Please use a more specific exception type

2023-05-17 12:33 UTC, ct2034 commented on ros2diagnostics_cli/ros2diagnostics_cli/api/__init__.py
> +    b'\x03': ('STALE', RED + 'STALE' + COLOR_DEFAULT),
Please use the constants declared in  dagnostic_msgs.msg.DiagnosticStatus

2023-05-17 12:33 UTC, ct2034 commented on ros2diagnostics_cli/package.xml
> +  <depend>ros2cli</depend>
All required packages from this repo must be declared here

2023-05-17 12:33 UTC, ct2034 commented on ros2diagnostics_cli/ros2diagnostics_cli/api/__init__.py
> +    b'\x03': ('STALE', RED + 'STALE' + COLOR_DEFAULT),
And you can also use f-strings here

2023-05-17 12:33 UTC, ct2034 commented on ros2diagnostics_cli/ros2diagnostics_cli/verb/csv.py
> +                print(str(error))
```suggestion
                print(error)
```

2023-05-17 12:33 UTC, ct2034 commented on ros2diagnostics_cli/ros2diagnostics_cli/verb/csv.py
> +            for kv in status.values:
```suggestion
            line.extend(kv.value for kv in status.values)
```

2023-05-17 12:33 UTC, ct2034 commented on ros2diagnostics_cli/ros2diagnostics_cli/verb/csv.py
> +        level_name, _ = convert_level_to_str(status.level)
I don't see how this is imported

2023-05-17 12:33 UTC, ct2034 commented on ros2diagnostics_cli/ros2diagnostics_cli/api/__init__.py
> +            return False
```suggestion
        return False if not self.__levels else level not in self.__levels
```

2023-05-17 12:33 UTC, ct2034 commented on ros2diagnostics_cli/ros2diagnostics_cli/api/__init__.py
> +    parser.add_argument('-1', '--once', action='store_true', help='run only once')
```suggestion
    parser.add_argument(
        '-1', 
        '--once', 
        action='store_true', 
        help='run only once')
```

2023-05-17 12:33 UTC, ct2034 commented on ros2diagnostics_cli/ros2diagnostics_cli/api/__init__.py
> +        '-f', '--filter', type=str, help='filter diagnostic status name'
```suggestion
        '-f', 
        '--filter', 
        type=str, 
        help='filter diagnostic status name'
```

2023-07-31 01:03 UTC, russkel commented
This looks useful - has there been movement on this?

2023-09-19 03:16 UTC, russkel commented
@robobe do you mind if I take over this PR if you're not interested/don't have the time?

2023-09-26 13:02 UTC, ct2034 commented
Hi @russkel, thanks for your interest. Since @robobe is fairly unresponsive for quite some time, please feel free to take this over.

2023-09-27 08:46 UTC, russkel commented
Hi @ct2034 will do when I get some time.

2023-10-07 01:40 UTC, russkel commented
Hi @ct2034 

I have begun the work: https://github.com/russkel/diagnostics/tree/ros2cli_diagnostics

I have addressed your suggestions and am going to do the following:

* rename to `ros2diagnostics` to follow convention
* as per your suggestion change verbs to list/echo.
* convert csv to an output format option on echo: `ros2 diagnostics echo -f csv > my-csv.csv` (unix philosophy)
* add self test verb

2023-12-12 16:11 UTC, ct2034 commented
Thanks for your work @russkel. I can not edit the branch this PR is from. Please create a new one. Than I can close this one

2026-04-20 14:50 UTC, ct2034 commented
Feel free to reopen

2026-04-20 14:50 UTC, closed without merging