Port cpu_monitor to ROS2
ros/diagnostics pull request #326
Opened 2024-01-17 10:13 UTC by RichardvdK

I attempted to port the cpu_monitor to ROS2. The module allows users to monitor the CPU usage of their system in real time. It publishes the usage percentage in a diagnostic message.

- I kept the ros arguments warning_percentage and window.
- Added 3 unit tests to cover the code

Let me know what you think! :)

2024-01-25 14:19 UTC, ct2034 requested changes
Thanks for porting this. Please see the inline comments

2024-01-25 14:19 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/cpu_monitor.py
> +import collections
```suggestion
from collections import deque
```

2024-01-25 14:19 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/cpu_monitor.py
> +        self._readings = collections.deque(maxlen=window)
```suggestion
        self._readings = deque(maxlen=window)
```

2024-01-25 14:19 UTC, ct2034 commented on diagnostic_common_diagnostics/test/systemtest/test_cpu_monitor.py
> +        time.sleep(0.1)
Please move this to a setUp() method (https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp).
Should have afaik the same effect.

2024-01-25 14:19 UTC, ct2034 commented on diagnostic_common_diagnostics/test/systemtest/test_cpu_monitor.py
> +        time.sleep(0.1)
see line 64

2024-01-25 14:19 UTC, ct2034 commented on diagnostic_common_diagnostics/test/systemtest/test_cpu_monitor.py
> +        time.sleep(0.1)
see line 64

2024-01-28 14:23 UTC, RichardvdK commented
> Thanks for porting this. Please see the inline comments

Thanks for reviewing! I updated the files accordingly :)

2024-02-08 11:51 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/cpu_monitor.py
> +        self._readings = collections.deque(maxlen=window)
```suggestion
        self._readings = deque(maxlen=window)
```

2024-02-08 11:53 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/cpu_monitor.py
> +        self._readings = collections.deque(maxlen=window)
This is not resolved. Please implement this change

2024-02-08 11:57 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/cpu_monitor.py
> +        stat.add('CPU Load Average', '{:.2f}'.format(cpu_average))
Please use f-string

2024-02-08 11:57 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/cpu_monitor.py
> +            stat.add('CPU {} Load'.format(idx), '{:.2f}'.format(cpu_percentage))
Please use f-string

2024-02-08 11:57 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/cpu_monitor.py
> +                         'At least one CPU exceeds {} percent'.format(self._warning_percentage))
Please use f-string

2024-02-08 11:57 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/cpu_monitor.py
> +                         'CPU Average {:.2f} percent'.format(cpu_average))
Please use f-string

2024-02-08 11:57 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/cpu_monitor.py
> +    node = Node('cpu_monitor_%s' % hostname.replace('-', '_'))
Please use f-string

2024-02-14 09:05 UTC, ct2034 requested changes
Please fix the failing tests

2024-02-15 09:43 UTC, ct2034 requested changes
Please fix 
- SyntaxError in diagnostic_common_diagnostics/cpu_monitor.py:95

2024-02-15 13:32 UTC, RichardvdK commented
@ct2034 Excuse moi! Everything should be fixed now :)

2024-02-15 16:00 UTC, ct2034 requested changes
Sorry, I wanted to make these changes myself but could not push to your branch

2024-02-15 16:00 UTC, ct2034 commented on diagnostic_common_diagnostics/CMakeLists.txt
> +        test/systemtest/test_cpu_monitor.py
```suggestion
        test_cpu_monitor
        test/systemtest/test_cpu_monitor.py
        TIMEOUT 10)
    ament_add_pytest_test(
        test_ntp_monitor
        test/systemtest/test_ntp_monitor.py
```

Alphabetical ordering

2024-02-15 16:00 UTC, ct2034 commented on diagnostic_common_diagnostics/README.md
> +
Please also move this above ntp_montior. Then add the subsections ### Published Topics and ### Parameters, similarly to how it is done for ntp_monitor

2024-02-15 16:00 UTC, ct2034 commented on diagnostic_common_diagnostics/mainpage.dox
> +- cpu_monitor publishes diagnostic messages with the CPU usage of the system.
```suggestion
- cpu_monitor publishes diagnostic messages with the CPU usage of the system.
- ntp_monitor publishes diagnostic messages for how well the NTP time sync is working.
```

2024-02-15 16:00 UTC, ct2034 commented on diagnostic_common_diagnostics/package.xml
> +
Please reduce the number of changes here to what is necessary

2024-03-22 09:04 UTC, RichardvdK commented
@ct2034 did you find time already to re-review this PR? :)

2024-03-22 10:36 UTC, ct2034 approved these changes

2024-03-22 10:37 UTC, merged

2024-07-17 13:15 UTC, ct2034 commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|ros2-jazzy|[<img src="https://img.shields.io/github/pulls/detail/state/ros/diagnostics/385">](https://github.com/ros/diagnostics/pull/385)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

<!--- Backport version: 9.5.1 -->