Add add_analyzer functionality
ros/diagnostics pull request #329
Opened 2024-01-22 13:17 UTC by MartinCornelis2

Applied the following changes to allow adding analyzers at runtime similar to the ROS1 functionality. 

- Move the creation of `analyzer_group_ ` and `other_analyzer_` from the constructor to a new function `initAnalyzers()`.
- Added a subscriber to parameter events `param_sub_` that triggers a callback `parameterCallback`.
- Check in the callback if `this` node got any new paramters -> if true, lock the mutex and call `initAnalyzers()` again.

- Created an `add_analyzer` node that forwards its own parameters to the `diagnostic_aggregator` by sending a request to `/diagnostics_agg/set_parameters_atomically` service
- The `add_analyzer` looks for all parameters starting with the prefix `analyzers.`, converts them to a parameter_msg and sends them together as one `SetParametersAtomically::Request`

Example usage:
```
<node name="add_my_analyzer" pkg="diagnostic_aggregator" exec="add_analyzer" >
        <param from="$(find-pkg-share <pkg_name>)/param/<param_file_path>.yaml" allow_substs="true"/>
        <remap from="/diagnostics_agg/set_parameters_atomically" to="/diagnostics_autonomy/set_parameters_atomically" />
</node>
```

2024-01-25 14:25 UTC, ct2034 requested changes
Thanks for adding this feature.
Please add 
- information on the usage in diagnostic_aggregator/README.md
- a test that initializes a new analyzer at runtime

2024-03-01 13:39 UTC, MartinCornelis2 commented on diagnostic_aggregator/CMakeLists.txt
> +  foreach(test_name ${add_analyzers_tests})
I followed the previous pattern even though I only provide a test for one of them. I can remove the loop or add the expected outcome for the other analyzers, or just leave this as is.

2024-03-27 14:52 UTC, Timple commented
Looks like all comments where addressed. Any chance for a re-review?

2024-06-27 06:33 UTC, Timple commented
If I may be so bold... Since there's a lot of maintenance effort going on: can this get a re-review? :slightly_smiling_face:

2024-06-27 06:35 UTC, ct2034 commented
Of course. Let's use the momentum while it lasts ;-)

2024-06-27 06:39 UTC, ct2034 approved these changes

2024-06-27 06:39 UTC, ct2034 commented on diagnostic_aggregator/CMakeLists.txt
> +  foreach(test_name ${add_analyzers_tests})
thats ok. This way it could be extended later

2024-06-27 06:42 UTC, ct2034 commented
https://build.ros2.org/job/Rpr__diagnostics__ubuntu_noble_amd64/27/ fails due to https://github.com/PyCQA/flake8/issues/646

2024-06-27 06:42 UTC, merged

2024-06-27 06:43 UTC, ct2034 commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|ros2-humble|[<img src="https://img.shields.io/github/pulls/detail/state/ros/diagnostics/359">](https://github.com/ros/diagnostics/pull/359)|
|✅|ros2-iron|[<img src="https://img.shields.io/github/pulls/detail/state/ros/diagnostics/360">](https://github.com/ros/diagnostics/pull/360)|
|✅|ros2-jazzy|[<img src="https://img.shields.io/github/pulls/detail/state/ros/diagnostics/361">](https://github.com/ros/diagnostics/pull/361)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

<!--- Backport version: 9.5.1 -->