refactor(ram_monitor): ros2 port
ros/diagnostics pull request #338
Opened 2024-04-09 13:53 UTC by reinzor

2024-04-26 11:12 UTC, reinzor commented
ping @ct2034

2024-05-14 08:55 UTC, ct2034 commented
Tested locally ✅

2024-05-14 09:00 UTC, ct2034 requested changes

2024-05-14 09:00 UTC, ct2034 commented on diagnostic_common_diagnostics/README.md
> +  * window: the maximum length of the used collections.deque for queuing CPU readings.
```suggestion
  * window: the maximum length of the used collections.deque for queuing RAM readings.
```
(I guess)

2024-05-14 09:00 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/ram_monitor.py
> +            node.declare_parameter('warning_percentage', 90.0).value,
```suggestion
            node.declare_parameter('warning_percentage', 90).value,
```
Why set it as float here, then cast it to an int?

2024-05-14 09:00 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/ram_monitor.py
> +    def __init__(self, warning_percentage, window=1):
```suggestion
    def __init__(self, warning_percentage, window):
```
I think default value makes more sense on ROS level

2024-05-14 09:00 UTC, ct2034 commented on diagnostic_common_diagnostics/diagnostic_common_diagnostics/ram_monitor.py
> +        stat.add('RAM Load Average', '{:.2f}'.format(ram_average))
Please use f-strings everywhere

2024-05-24 11:48 UTC, reinzor commented
@ct2034 , can we merge this?

2024-06-14 12:56 UTC, reinzor commented
ping @ct2034

2024-06-26 15:40 UTC, merged