NTP monitor improvements
ros/diagnostics pull request #342
Opened 2024-04-29 08:37 UTC by tonynajjar

1. Adds timestamp to diagnostics message
2. Removes unecessary double timer - instead check and publish in same callback (open to debate)
3. parameterize timer frequency
4. fix filtering of ros-args to ignore all args (e.g. --params-file as well)

2024-05-13 12:58 UTC, ct2034 approved these changes
Thanks for the contribution :)

2024-05-14 09:04 UTC, ct2034 requested changes
Please fix the linter issues. I can't push to your fork

2024-05-14 09:16 UTC, tonynajjar commented
> Please fix the linter issues. I can't push to your fork

done

2024-05-14 11:52 UTC, ct2034 approved these changes

2024-05-14 14:03 UTC, merged