Add starting_up_state parameter to Updater
ros/diagnostics pull request #354
Opened 2024-06-17 14:21 UTC by redvinaa

In the current implementation, when the Updater object is constructed, it sends off an "OK" signal. This could be problematic if we consider "Everything is *running* as expected" (definition of "OK" status as per REP107), that running is already initialized.

The default behavior doesn't change with this PR, so it wouldn't break anything.
Also, in the python implementation, None can be passed to skip "Node starting up" status publishing altogether.

2024-11-15 10:49 UTC, redvinaa commented
Hi! Can I get an update on this one?

If it wasn't merged because of this test case failing, can I get some help understanding the error? I'm sure a few minutes of someone who already understands these template-based tests can save me hours of trial and error.
After that I can also rebase to fix the conflict.

2025-02-10 15:07 UTC, ct2034 commented
Hi @redvinaa.
Could we please have a quick discussion about this? I am not sure if it is worth the extra overhead. Yes, 
> "Everything is running as expected" (definition of "OK" status as per REP107)
On the other hand, I also would not like my system starting in an error state. Your issue could also be solved by additional state, such as proposed in https://github.com/ros2/common_interfaces/issues/268. What is your opinion about that?

2025-06-04 13:48 UTC, redvinaa commented
Hi! Sorry for the long delay. It's possible that it would make sense to add new states, but that's a huge change and it appears to be moving very slowly. This PR on the other hand is not breaking, and I think is still useful until the new states get added.

2026-04-20 13:23 UTC, ct2034 approved these changes

2026-04-20 14:36 UTC, ct2034 requested changes

2026-04-20 14:36 UTC, ct2034 commented on diagnostic_updater/src/diagnostic_updater.cpp
> +  }
what is the purpose of this line?

2026-04-20 14:50 UTC, ct2034 requested changes

2026-04-20 14:50 UTC, ct2034 commented on diagnostic_updater/include/diagnostic_updater/diagnostic_updater.hpp
> +    int starting_up_status = diagnostic_msgs::msg::DiagnosticStatus::OK)
```suggestion
    unsigned char starting_up_status = diagnostic_msgs::msg::DiagnosticStatus::OK)
```

2026-04-20 14:50 UTC, ct2034 commented on diagnostic_updater/include/diagnostic_updater/diagnostic_updater.hpp
> +    int starting_up_status = diagnostic_msgs::msg::DiagnosticStatus::OK);
```suggestion
    unsigned char starting_up_status = diagnostic_msgs::msg::DiagnosticStatus::OK);
```

2026-04-20 14:50 UTC, ct2034 commented on diagnostic_updater/include/diagnostic_updater/diagnostic_updater.hpp
> +  int starting_up_status_;
```suggestion
  unsigned char starting_up_status_;
```

2026-04-20 14:50 UTC, ct2034 commented on diagnostic_updater/src/diagnostic_updater.cpp
> +  int starting_up_status)
```suggestion
  unsigned char starting_up_status)
```

2026-04-20 15:14 UTC, redvinaa commented on diagnostic_updater/src/diagnostic_updater.cpp
> +  }
I don't remember anymore, removing

2026-05-04 12:11 UTC, redvinaa commented
I think the xmllint failure is not coming from this PR (no xml was modified). Otherwise, all requested changes have been addressed.

2026-05-20 16:49 UTC, merged