Stop flooding the terminal by default with all matches, switch to debug if desired
ros/diagnostics pull request #364
Opened 2024-06-27 07:49 UTC by MCFurry

We noticed that when extending a ROS system with many analyzers, the terminal during startup is flooded with all the analyzer matches.
I reckon these can be debug logs that one can enable when desired.

(Example in the tests, since these require these stdout logs)

2025-02-20 10:30 UTC, Timple commented
```
The following tests FAILED:
	  2 - ntp_monitor_launchtest (Failed)
```
This monitor was not modified in this PR. I'll rebase to see if that helps.

2025-03-27 14:02 UTC, Timple commented
Ping @ct2034 Any objections here?

2025-04-15 07:31 UTC, Timple commented
Or can this at least get in before Kilted? :slightly_smiling_face: 
It's coming up! https://discourse.ros.org/t/upcoming-ros-2-feature-freeze-for-kilted-kaiju-on-april-14th/43096/2

2025-04-15 07:50 UTC, ct2034 requested changes

2025-04-15 07:50 UTC, ct2034 commented on diagnostic_aggregator/include/diagnostic_aggregator/generic_analyzer_base.hpp
> +    RCLCPP_DEBUG(
Can we please keep those messages that are not triggered per match on info

2025-04-15 08:00 UTC, ct2034 commented
Hey @MCFurry @Timple 
Thanks for the contribution.
I am a little reluctant against changing the logging level in the code, because that is something that can be done depending on the runtime.
But I agree that it is generally a good idea to not have messages that are emitted repeatedly (like per match) in info.
So, I am asking you to please change all those messages that are emitted only once per initialization back to info.

2025-05-23 11:45 UTC, Timple commented
Sorry it took a while!

2025-05-26 12:07 UTC, ct2034 commented
Based on what we discussed above, that I am happy to change the level in the `match` method. I would therefore expect no changes in the `init` method of `diagnostic_aggregator/src/analyzer_group.cpp`. Or are there any reasons to also change those tha I am missing right now?

In any case, I think this would also be a good use for [RCLCPP_DEBUG_THROTTLE](https://docs.ros2.org/latest/api/rclcpp/logging_8hpp.html#a11ad0ece390eff7363cc60c0cd55a3ba). What do you think?

2025-05-26 12:38 UTC, Timple commented
The issue is that there a loop around all parameters:
```c++
for (const auto & param : parameters) {
```

Every analyzer added prints information about all other analyzers as well. Since we have a lot of analyzers, adding only 1 causes a massive print flood.

2025-06-12 05:41 UTC, Timple commented
@ct2034 if you like things to be verbose, do you have any ideas how to get around printing always all parameters?

2026-05-20 22:34 UTC, ct2034 requested changes

2026-05-20 22:34 UTC, ct2034 commented on diagnostic_aggregator/src/analyzer_group.cpp
> -    RCLCPP_INFO(
Could we not change these? They don't get executed per match, or do they?

2026-05-20 22:34 UTC, ct2034 commented on diagnostic_aggregator/src/analyzer_group.cpp
> -      RCLCPP_INFO(
Could we not change these? They don't get executed per match, or do they?

2026-05-21 08:09 UTC, Timple commented on diagnostic_aggregator/src/analyzer_group.cpp
> -    RCLCPP_INFO(
Not per match, but per init. And every time a`add_analyzer` triggers a parameter event, it fully destroys and fully rebuilds the entire `AnalyzerGroup`. So this does lead to excessive logging.

2026-05-21 08:27 UTC, ct2034 commented on diagnostic_aggregator/src/analyzer_group.cpp
> -    RCLCPP_INFO(
Okay, so I guess the flooding here only ocurrs in scenarios with dynamic configuration.
Could we do something where it is an info if the aggregator is new and else debug? Would this work. It would make the implementation slightly more complex, though

2026-05-21 08:49 UTC, Timple commented on diagnostic_aggregator/src/analyzer_group.cpp
> -    RCLCPP_INFO(
In anticipation of this request I already dived into that.

- Pragmatic approach:
  - Track existing analyzer names before re-init, then suppress logs for already-known ones.

- Support incremental adds
  - Quite significant rewrite (including some bookkeeping).

- Making log level a user preference
  - Quite easy with a parameter I guess.
  
 I am currently trying option 1

2026-05-21 09:03 UTC, Timple commented on diagnostic_aggregator/src/analyzer_group.cpp
> -    RCLCPP_INFO(
https://github.com/ros/diagnostics/commit/1c8d8b84504c1b4fc4b34249a7f5ed7e72d3d210 

I guess this is a bit much for only a log statement..

2026-05-21 09:08 UTC, Timple commented on diagnostic_aggregator/src/analyzer_group.cpp
> -    RCLCPP_INFO(
Perhaps a compromise: We'll make this a `ROS_INFO` but the matches (which are much more verbose) a `ROS_DEBUG`?

2026-05-21 14:56 UTC, ct2034 commented on diagnostic_aggregator/src/analyzer_group.cpp
> -    RCLCPP_INFO(
Yes, I think that is a good compromise :)

2026-05-21 14:58 UTC, Timple commented on diagnostic_aggregator/src/analyzer_group.cpp
> -    RCLCPP_INFO(
Done!

2026-05-21 15:03 UTC, ct2034 approved these changes

2026-05-21 15:04 UTC, merged