Custom names for FrequencyStatus and TimeStampStatus
ros/diagnostics pull request #86
Opened 2018-08-16 14:58 UTC by icolwell

Expanded on #84 to allow custom names for both of the provided diagnostic tasks (FrequencyStatus and TimeStampStatus). Also provided the same functionality for the python API.

Looks like my editor caught some trailing white space. Let me know if you'd like those differences removed.

2018-08-18 18:24 UTC, trainman419 requested changes
Looks great aside from the C++11 features that have crept in. Unfortunately this code still has to support C++03 😭

2018-08-18 18:25 UTC, trainman419 reviewed
Looks great aside from the C++11 features that have crept in. Unfortunately this code still has to support C++03 😭

2018-08-18 18:25 UTC, trainman419 commented on diagnostic_updater/include/diagnostic_updater/update_functions.h
> +        FrequencyStatus(params, "Frequency Status") {}
While this is convenient, delegating constructors is a C++11 feature, and this package is still supporting Indigo which only supports C++03.

2018-08-18 18:25 UTC, trainman419 commented on diagnostic_updater/include/diagnostic_updater/update_functions.h
> +        TimeStampStatus(params, "Timestamp Status") {}
Same here, delegating constructors is a C++11 feature, and this package is still supporting Indigo which only supports C++03.

2018-08-19 15:47 UTC, icolwell commented
Wasn't aware of the C++03 requirement, thanks for pointing that out! All fixed now.

2018-08-19 17:28 UTC, trainman419 approved these changes

2018-08-19 17:28 UTC, merged

2018-08-19 17:29 UTC, trainman419 commented
Thanks!